# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - statusapp1

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Azure Managed Identity config
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish StatusApp-Server -c Release --property PublishDir=${{env.DOTNET_ROOT}}/myapp
  
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./.github/bicep/main.bicep
          outputFilePath: ./.github/bicep/azuredeploy.json
  
      - name: Upload bicep for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: bicep
          path: ./.github/bicep

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: .net-app
  
      - name: Download bicep from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: bicep
  
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: StatusApp
          template: ./azuredeploy.json
          parameters: ./main.parameters.json

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'statusapp1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EFFE800C8A5645BB9635F12C24CA380D }}
          package: .
  
  deploy-webui:
    needs: build
    uses: ./.github/workflows/azure-static-web-apps-red-ground-0805be400.yml
    secrets: inherit